import type { Metadata } from "next";
import "./globals.css";
import { Press_Start_2P, Raleway } from "next/font/google";

const pressStart2P = Press_Start_2P({ subsets: ["latin"], weight: "400" });
const raleway = Raleway({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pressStart2P.className} ${raleway.className}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
